<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Day 2 | Exercise 3</title>
</head>

<body>
  <h1>Submit your details</h1>
  <!--
    TODO:
    - create a form which posts to the '/submit' endpoint
    - it should send a "name" and an "email"
  -->

  <!--
    TODO: Remove
  -->
  <form action="/submit" method="post">
    <input type="text" name="name">
    <input type="email" name="email">
    <button type="submit">Submit</button>
  </form>
</body>

</html>
